### ISSUE TITLE
Hardcoded link to external resources (pydev)

### ISSUE THREAD

**Issue by Harvester62** [black-h0bB1T/Asset-Flinger#1]
I downloaded and copied your add-on into the ..\scripts\addons_extern folder (I still use that configuration and have modified the file addon_utils.py to keep all external add-ons separated from the official ones, just before you ask it), and as soon as I activate it in the Preferences I get this error: 
Traceback (most recent call last):
  File "D:\Blender_2.78_stable\2.78\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "D:\Blender_2.78_stable\2.78\scripts\addons_extern\add_mesh_asset_flinger\__init__.py", line 867, in <module>
    import pydevd
ImportError: No module named 'pydevd'

The problem seems due to the hardcoded nature of the pydev source directory in the __init__.py file as it is below at line 867 and followings:
PYDEV_SOURCE_DIR = "C:\\devel\\apps\\eclipse-neon-pydev\\plugins\\org.python.pydev_5.8.0.201706061859\\pysrc"
import sys
if PYDEV_SOURCE_DIR not in sys.path:
    sys.path.append(PYDEV_SOURCE_DIR)
import pydevd
pydevd.settrace()

Obviously in my system that path doesn't exist and Blender returns an error message. Thanks.

**Comment by Harvester62** [comment]
OK, I've the solution. Comparing your file with the forked one I understood that possibly those last lines of code in the __init__.py file were possibly used by you only with Eclipse for programming the add-on. So, after commenting those lines from line 867 and saved the file, the add-on get activated and running in Blender 2.78c. Perhaps you might comment those lines before you push the add-on to the repository or add a note in the readme, but it's only a suggestion.

**Comment by black-h0bB1T** [comment]
Hello Harvester62, it seems you've cloned the repository and not downloaded the offical package 0.3, than yeah, you will get this issue. These lines allow me to debug the script in eclipse. Commenting them out should fix it. I'll try to do this is a better solution in the future :-)
